In [418]:
from sklearn.metrics import classification_report, confusion_matrix
from sklearn.neighbors import KNeighborsClassifier
from sklearn.model_selection import train_test_split
import pandas as pd
import numpy as np
import seaborn as sns

In [419]:
churn_df = pd.read_csv('churn_df.csv', index_col=0)
X = churn_df.drop("churn", axis = 1).values
y = churn_df['churn'].values
knn = KNeighborsClassifier(n_neighbors=7)
X_train, X_test, y_train, y_test = train_test_split(X,y, test_size = 0.4, random_state = 42)

knn.fit(X_train, y_train)
y_pred = knn.predict(X_test)
print(y_test.shape)
print(y_pred.shape)
print(confusion_matrix(y_test, y_pred))

(1334,)
(1334,)
[[1106   11]
 [ 183   34]]


In [420]:
music_df = pd.read_csv('music.csv')

print(music_df.info())

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1000 entries, 0 to 999
Data columns (total 13 columns):
 #   Column            Non-Null Count  Dtype  
---  ------            --------------  -----  
 0   Unnamed: 0        1000 non-null   int64  
 1   popularity        1000 non-null   int64  
 2   acousticness      1000 non-null   float64
 3   danceability      1000 non-null   float64
 4   duration_ms       1000 non-null   float64
 5   energy            1000 non-null   float64
 6   instrumentalness  1000 non-null   float64
 7   liveness          1000 non-null   float64
 8   loudness          1000 non-null   float64
 9   speechiness       1000 non-null   float64
 10  tempo             1000 non-null   float64
 11  valence           1000 non-null   float64
 12  genre             1000 non-null   object 
dtypes: float64(10), int64(2), object(1)
memory usage: 101.7+ KB
None


In [421]:
music_dummies = pd.get_dummies(music_df['genre'],drop_first=True)
print(music_dummies.head())

   Anime  Blues  Classical  Country  Electronic  Hip-Hop   Jazz    Rap   Rock
0  False  False      False    False       False    False   True  False  False
1  False  False      False    False       False    False  False   True  False
2  False  False      False    False        True    False  False  False  False
3  False  False      False    False       False    False  False  False   True
4  False  False      False    False       False    False  False   True  False


In [422]:
music_df = pd.read_csv('music.csv', index_col = 0)
music_dummies = pd.get_dummies(music_df['genre'], drop_first=True)

#music_dummies.head()
music_dummies = pd.concat([music_df, music_dummies], axis = 1)
music_dummies = music_dummies.drop('genre', axis=1)
#music_dummies.head()
print(music_dummies.columns)

from sklearn.model_selection import cross_val_score, KFold
from sklearn.linear_model import LinearRegression

X = music_dummies.drop('popularity', axis=1).values
y = music_dummies['popularity'].values
X_train, X_test, y_train, y_test = train_test_split(X,y, test_size=0.2,
                                                   random_state=42)
kf = KFold(n_splits=5, shuffle=True, random_state=42)
linreg = LinearRegression()
linreg_cv = cross_val_score(linreg, X_train, y_train, cv=kf,
                           scoring='neg_mean_squared_error')

print(np.sqrt(-linreg_cv))

Index(['popularity', 'acousticness', 'danceability', 'duration_ms', 'energy',
       'instrumentalness', 'liveness', 'loudness', 'speechiness', 'tempo',
       'valence', 'Anime', 'Blues', 'Classical', 'Country', 'Electronic',
       'Hip-Hop', 'Jazz', 'Rap', 'Rock'],
      dtype='object')
[8.15810501 8.63114581 7.52281687 8.62016985 7.91296943]


In [423]:
music_df.head()

popularity  acousticness  danceability  duration_ms  energy  \
0          41        0.6440         0.823     237000.0   0.814   
1          62        0.0855         0.686     154000.0   0.670   
2          42        0.2390         0.669     218000.0   0.736   
3          64        0.0125         0.522     246000.0   0.923   
4          60        0.1210         0.780     229000.0   0.467   

   instrumentalness  liveness  loudness  speechiness    tempo  valence  \
0          0.687000     0.117    -5.611        0.177  102.619    0.649   
1          0.000000     0.120    -7.626        0.225  173.915    0.636   
2          0.000169     0.598    -3.223        0.060  145.061    0.494   
3          0.017000     0.085    -4.560        0.054  120.406    0.595   
4          0.000134     0.314    -6.645        0.253   96.056    0.312   

        genre  
0        Jazz  
1         Rap  
2  Electronic  
3        Rock  
4         Rap

In [424]:
knn = KNeighborsClassifier(n_neighbors=5)
knn.fit(X_train_num, y_train)
y_pred = knn.predict(X_test_num)
print(knn.score(X_test_num, y_test))

ValueError: Found input variables with inconsistent numbers of samples: [713, 800]

In [393]:
from sklearn.impute import SimpleImputer
X_cat = music_df['genre'].values.reshape(-1,1)
X_num = music_df.drop(['genre', 'popularity'], axis = 1).values
y = music_df['popularity'].values
X_train_cat, X_test_cat, y_train, y_test =  train_test_split(X_cat, y , test_size=0.2,random_state=12)

X_train_num, X_test_num, y_train, y_test =  train_test_split(X_num, y , test_size=0.2,random_state=12)

imp_cat = SimpleImputer(strategy="most_frequent")
X_train_cat = imp_cat.fit_transform(X_train_cat)
X_test_cat = imp_cat.transform(X_test_cat)

imp_num = SimpleImputer()
X_train_num = imp_num.fit_transform(X_train_num)
X_test_num = imp_num.transform(X_test_num)

X_train = np.append(X_train_num,X_train_cat,axis = 1)
X_test = np.append(X_test_num,X_test_cat,axis = 1)

In [394]:
columns = ['acousticness', 'danceability', 'duration_ms', 'energy',
           'instrumentalness', 'liveness', 'loudness', 'speechiness', 'tempo',
           'valence', 'genre']

check = pd.DataFrame(X_train, columns=columns)

print(check.isna().sum().sort_values())


acousticness        0
danceability        0
duration_ms         0
energy              0
instrumentalness    0
liveness            0
loudness            0
speechiness         0
tempo               0
valence             0
genre               0
dtype: int64


In [395]:
knn = KNeighborsClassifier(n_neighbors=5)
knn.fit(X_train_num, y_train)
y_pred = knn.predict(X_test_num)
print(knn.score(X_test_num, y_test))

0.015


In [396]:
from sklearn.pipeline import Pipeline
from sklearn.linear_model import LogisticRegression


In [ ]:
music_df = pd.read_csv('music_unclean.csv', index_col = 0)
music_df = music_df.dropna(subset=['genre','popularity','loudness','liveness','tempo'])
music_df['genre'] = np.where(music_df['genre'] == 'Rock', 1, 0)
X = music_df.drop('genre', axis = 1).values
y = music_df['genre'].values
X_train, X_test, y_train, y_test = train_test_split(X,y,test_size=0.3,random_state=42)

imp = SimpleImputer()
logres = LogisticRegression()
steps = [('imputation', imp),
                 ('Log_reg', logres)]

steps = [('imputation', SimpleImputer()),
         ('Log_reg', LogisticRegression(max_iter = 100000))]

pipeline = Pipeline(steps)
pipeline.fit(X_train, y_train)

y_pred = pipeline.predict(X_test)
print(confusion_matrix(y_test, y_pred))
print(pipeline.score(X_test,y_test))


[[103  32]
 [ 11 122]]
0.8395522388059702


In [398]:
music_df = pd.read_csv('music_unclean.csv')

print(music_df.isna().sum())

Unnamed: 0            0
popularity           31
acousticness        200
danceability        143
duration_ms          91
energy              200
instrumentalness     91
liveness             46
loudness             44
speechiness          59
tempo                46
valence             143
genre                 8
dtype: int64


In [399]:
music_df = music_df.dropna(subset=["genre", "popularity", "loudness", "liveness", "tempo"])

print(music_df.isna().sum().sort_values())
print("Shape of the `music_df`: {}".format(music_df.shape))

# Convert genre to a binary feature
music_df["genre"] = np.where(music_df["genre"] == "Rock", 1, 0)

X = music_df.drop('genre', axis = 1).values
y = music_df['genre'].values

X_train, X_test, y_train, y_test = train_test_split(X,y,test_size=0.3,random_state=42)
# Instantiate an imputer
imputer = SimpleImputer()
X_train = imputer.fit_transform(X_train) ###################
X_test = imputer.transform(X_test)          ###################

# Instantiate a knn model
knn = KNeighborsClassifier(n_neighbors=3)

# Build steps for the pipeline
steps = [("imputer", imputer), 
         ("knn", knn)]

# Create the pipeline
pipeline = Pipeline(steps)

# Fit the pipeline to the training data
pipeline.fit(X_train, y_train)

# Make predictions on the test set
y_pred = pipeline.predict(X_test)

# Print the confusion matrix

print(confusion_matrix(y_test, y_pred))
print(pipeline.score(X_test,y_test))


Unnamed: 0            0
popularity            0
liveness              0
loudness              0
tempo                 0
genre                 0
duration_ms          29
instrumentalness     29
speechiness          53
danceability        127
valence             127
acousticness        178
energy              178
dtype: int64
Shape of the `music_df`: (892, 13)
[[69 66]
 [66 67]]
0.5074626865671642


In [400]:
music_df = music_df.dropna(subset=["genre", "popularity", "loudness", "liveness", "tempo"])

print(music_df.isna().sum().sort_values())
print("Shape of the `music_df`: {}".format(music_df.shape))

# Convert genre to a binary feature
music_df["genre"] = np.where(music_df["genre"] == "Rock", 1, 0)

X = music_df.drop('genre', axis = 1).values
y = music_df['genre'].values

X_train, X_test, y_train, y_test = train_test_split(X,y,test_size=0.3,random_state=42)
# Instantiate an imputer
imputer = SimpleImputer()
X_train = imputer.fit_transform(X_train) ###################
X_test = imputer.transform(X_test)          ###################

# Instantiate a knn model
knn = KNeighborsClassifier(n_neighbors=3)

# Build steps for the pipeline
steps = [("imputer", imputer), 
         ("knn", knn)]



Unnamed: 0            0
popularity            0
liveness              0
loudness              0
tempo                 0
genre                 0
duration_ms          29
instrumentalness     29
speechiness          53
danceability        127
valence             127
acousticness        178
energy              178
dtype: int64
Shape of the `music_df`: (892, 13)


In [401]:
music_df = pd.read_csv('music_unclean.csv')
music_df.head()

Unnamed: 0  popularity  acousticness  danceability  duration_ms  energy  \
0           0        64.0       0.69400         0.610     217000.0   0.590   
1           1        31.0       0.73900         0.565     261000.0   0.393   
2           2        57.0       0.00879         0.433     263000.0   0.815   
3           3        63.0       0.01050         0.359     564000.0   0.762   
4           4         NaN       0.30100         0.511          NaN   0.699   

   instrumentalness  liveness  loudness  speechiness    tempo  valence  genre  
0          0.000002     0.150    -7.325        0.036  137.838    0.352    NaN  
1          0.000845     0.143    -9.309        0.024   75.537    0.229  Anime  
2          0.000000     0.138    -3.658          NaN  125.358    0.461   Rock  
3          0.281000     0.368    -8.323        0.032   89.259    0.167   Rock  
4               NaN     0.088       NaN        0.037  120.406    0.496  Anime

In [402]:
# X_cat = music_df['genre'].values.reshape(-1,1)
# X_num = music_df.drop(['genre', 'popularity'], axis = 1).values
# y = music_df['popularity'].values
# X_train_cat, X_test_cat, y_train, y_test =  train_test_split(X_cat, y , test_size=0.2,random_state=12)

# X_train_num, X_test_num, y_train, y_test =  train_test_split(X_num, y , test_size=0.2,random_state=12)

# imp_cat = SimpleImputer(strategy="most_frequent")
# X_train_cat = imp_cat.fit_transform(X_train_cat)
# X_test_cat = imp_cat.transform(X_test_cat)

# imp_num = SimpleImputer()
# X_train_num = imp_num.fit_transform(X_train_num)
# X_test_num = imp_num.transform(X_test_num)

# X_train = np.append(X_train_num,X_train_cat,axis = 1)
# X_test = np.append(X_test_num,X_test_cat,axis = 1)

# columns = ['acousticness', 'danceability', 'duration_ms', 'energy',
#            'instrumentalness', 'liveness', 'loudness', 'speechiness', 'tempo',
#            'valence', 'genre']

# # check = pd.DataFrame(X_train, columns=columns)

# print(check.isna().sum().sort_values())

# knn = KNeighborsClassifier(n_neighbors=5)
# knn.fit(X_train_num, y_train)
# y_pred = knn.predict(X_test_num)
# print(knn.score(X_test_num, y_test))

In [425]:
music_df = music_df.dropna(subset=["genre", "popularity", "loudness", "liveness", "tempo"])

print(music_df.isna().sum().sort_values())
print("Shape of the `music_df`: {}".format(music_df.shape))

# Convert genre to a binary feature
music_df["genre"] = np.where(music_df["genre"] == "Rock", 1, 0)

X = music_df.drop('genre', axis = 1).values
y = music_df['genre'].values

X_train, X_test, y_train, y_test = train_test_split(X,y,test_size=0.3,random_state=42)
# Instantiate an imputer
imputer = SimpleImputer()
X_train = imputer.fit_transform(X_train) ###################
X_test = imputer.transform(X_test)          ###################

X_cat = music_df['genre'].values.reshape(-1,1)
X_num = music_df.drop(['genre', 'popularity'], axis = 1).values
y = music_df['popularity'].values
X_train_cat, X_test_cat, y_train, y_test =  train_test_split(X_cat, y , test_size=0.2,random_state=12)

X_train_num, X_test_num, y_train, y_test =  train_test_split(X_num, y , test_size=0.2,random_state=12)

imp_cat = SimpleImputer(strategy="most_frequent")
X_train_cat = imp_cat.fit_transform(X_train_cat)
X_test_cat = imp_cat.transform(X_test_cat)

imp_num = SimpleImputer()
X_train_num = imp_num.fit_transform(X_train_num)
X_test_num = imp_num.transform(X_test_num)

X_train = np.append(X_train_num,X_train_cat,axis = 1)
X_test = np.append(X_test_num,X_test_cat,axis = 1)

columns = ['acousticness', 'danceability', 'duration_ms', 'energy',
           'instrumentalness', 'liveness', 'loudness', 'speechiness', 'tempo',
           'valence', 'genre']

# check = pd.DataFrame(X_train, columns=columns)

print(check.isna().sum().sort_values())

knn = KNeighborsClassifier(n_neighbors=3)
knn.fit(X_train_num, y_train)
y_pred = knn.predict(X_test_num)
print(knn.score(X_test_num, y_test))


popularity          0
acousticness        0
danceability        0
duration_ms         0
energy              0
instrumentalness    0
liveness            0
loudness            0
speechiness         0
tempo               0
valence             0
genre               0
dtype: int64
Shape of the `music_df`: (1000, 12)
acousticness        0
danceability        0
duration_ms         0
energy              0
instrumentalness    0
liveness            0
loudness            0
speechiness         0
tempo               0
valence             0
genre               0
dtype: int64
0.025
